### ISSUE TITLE
PhantomJS leg error

### ISSUE THREAD

**Issue by aaawtest** [gpolitis/node-tarantula#27]
Very nice project.

Been trying to get phantomjs leg to work but getting errors.

/usr/local/bin/node --debug-brk=55858 --nolazy example-wikidive-phantom.js
debugger listening on port 55858
Crawling…  http://en.wikipedia.org/
GET http://en.wikipedia.org/
TypeError: Cannot call method 'map' of null
    at EventEmitter.Tarantula.push (/Volumes/peter/Dropbox/src2/longtail/jscrawler/tmp/node_modules/tarantula/lib/tarantula.js:158:15)
    at EventEmitter.<anonymous> (/Volumes/peter/Dropbox/src2/longtail/jscrawler/tmp/node_modules/tarantula/lib/tarantula.js:73:8)
    at EventEmitter.emit (events.js:106:17)
    at EventEmitter.Tarantula.legEvent (/Volumes/peter/Dropbox/src2/longtail/jscrawler/tmp/node_modules/tarantula/lib/tarantula.js:269:12)
    at PhantomClient._get (/Volumes/peter/Dropbox/src2/longtail/jscrawler/tmp/node_modules/tarantula/lib/client/PhantomClient.js:202:19)
    at PhantomClient.clientEval (/Volumes/peter/Dropbox/src2/longtail/jscrawler/tmp/node_modules/tarantula/lib/client/PhantomClient.js:233:4)
    at exports.create.options (/Volumes/peter/Dropbox/src2/longtail/jscrawler/tmp/node_modules/tarantula/node_modules/node-phantom-simple/node-phantom-simple.js:40:26)
    at IncomingMessage.poll_func (/Volumes/peter/Dropbox/src2/longtail/jscrawler/tmp/node_modules/tarantula/node_modules/node-phantom-simple/node-phantom-simple.js:455:17)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:943:16

**Comment by aaawtest** [comment]
Also tried google.com which got some mileage but then failed at the same spot.

/usr/local/bin/node --debug-brk=56163 --nolazy example-wikidive-phantom.js
debugger listening on port 56163
Crawling…  http://google.com
GET http://google.com
V:0 T:7 Q:7 +6
GET http://google.com/intl/zh-TW/policies/
V:1 T:21 Q:20 +14
GET http://google.com/language_tools?hl=zh-HK&authuser=0
GET http://google.com/advanced_search?hl=zh-HK&authuser=0
V:2 T:23 Q:21 +2
GET http://google.com/intl/zh-TW/ads/
TypeError: Cannot call method 'map' of null
    at EventEmitter.Tarantula.push (/Volumes/peter/Dropbox/src2/longtail/jscrawler/tmp/node_modules/tarantula/lib/tarantula.js:158:15)
    at EventEmitter.<anonymous> (/Volumes/peter/Dropbox/src2/longtail/jscrawler/tmp/node_modules/tarantula/lib/tarantula.js:73:8)
    at EventEmitter.emit (events.js:106:17)
    at EventEmitter.Tarantula.legEvent (/Volumes/peter/Dropbox/src2/longtail/jscrawler/tmp/node_modules/tarantula/lib/tarantula.js:269:12)
    at PhantomClient._get (/Volumes/peter/Dropbox/src2/longtail/jscrawler/tmp/node_modules/tarantula/lib/client/PhantomClient.js:202:19)
    at PhantomClient.clientEval (/Volumes/peter/Dropbox/src2/longtail/jscrawler/tmp/node_modules/tarantula/lib/client/PhantomClient.js:233:4)
    at exports.create.options (/Volumes/peter/Dropbox/src2/longtail/jscrawler/tmp/node_modules/tarantula/node_modules/node-phantom-simple/node-phantom-simple.js:40:26)
    at IncomingMessage.poll_func (/Volumes/peter/Dropbox/src2/longtail/jscrawler/tmp/node_modules/tarantula/node_modules/node-phantom-simple/node-phantom-simple.js:455:17)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:943:16

Process finished with exit code 1

**Comment by tsypa** [comment]
I got error with phantom leg

~/node_modules/tarantula/example-wikidive-phantom.js
Crawling…  http://en.wikipedia.org/
GET http://en.wikipedia.org/
TypeError: Cannot call method 'map' of null
    at EventEmitter.Tarantula.push (/home/tm/node_modules/tarantula/lib/tarantula.js:158:15)
    at EventEmitter.<anonymous> (/home/tm/node_modules/tarantula/lib/tarantula.js:73:8)
    at EventEmitter.emit (events.js:106:17)
    at EventEmitter.Tarantula.legEvent (/home/tm/node_modules/tarantula/lib/tarantula.js:269:12)
    at /home/tm/node_modules/tarantula/lib/client/PhantomClient.js:202:19
    at /home/tm/node_modules/tarantula/lib/client/PhantomClient.js:233:4
    at /home/tm/node_modules/tarantula/node_modules/node-phantom-simple/node-phantom-simple.js:40:26
    at IncomingMessage.<anonymous> (/home/tm/node_modules/tarantula/node_modules/node-phantom-simple/node-phantom-simple.js:455:17)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:929:16

**Comment by robcolburn** [comment]
@aaawtest @tsypa,
The problem in both cases is that you don't have PhantomJS installed. I've updated the docs and error messaging in v0.3.0 to clarify this requirement.
